# -*- coding: utf-8 -*-
"""covid 19(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_p_MuJA65eaXkQ_XXB8o78e1QmokYgN
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("covid_19.csv")

print("First 5 rows:")
print(data.head())

print("\nColumns in dataset:")
print(data.columns)

data = data.rename(columns={
    "Country/Region": "Country",
    "ObservationDate": "Date"
})

cols = [ "Country", "Confirmed", "Deaths", "Recovered", "Active"]
data = data[[col for col in cols if col in data.columns]]

if "Date" in data.columns:
    data["Date"] = pd.to_datetime(data["Date"])

data = data.dropna()

data = data.drop_duplicates()

print("\nCleaned Data Info:")
print(data.info())

print("\nTotal Confirmed Cases:", data["Confirmed"].sum())
print("Total Deaths:", data["Deaths"].sum())
print("Total Recovered:", data["Recovered"].sum())

print("\nStatistical Summary:")
print(data.describe())

top_countries = data.groupby("Country")["Confirmed"].sum().sort_values(ascending=False).head(10)

plt.figure()
top_countries.plot(kind="bar")
plt.title("Top 10 Affected Countries")
plt.xlabel("Country")
plt.ylabel("Confirmed Cases")
plt.xticks(rotation=45)
plt.show()

totals = data[["Confirmed", "Deaths", "Recovered"]].sum()

plt.figure()
totals.plot(kind="pie", autopct="%1.1f%%")
plt.title("COVID-19 Case Distribution")
plt.ylabel("")
plt.show()

plt.figure()
sns.scatterplot(x="Confirmed", y="Deaths", data=data)
plt.title("Confirmed vs Deaths")
plt.show()

plt.figure()
corr = data[["Confirmed", "Deaths", "Recovered", "Active"]].corr()
sns.heatmap(corr, annot=True)
plt.title("Correlation Heatmap")
plt.show()