# -*- coding: utf-8 -*-
"""covid 19 (new).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzzDPzX-Zp3UIW2ptqrnopBRsioCJTOd
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from google.colab import files

uploaded = files.upload()

data = pd.read_csv("covid_19 (2).csv")
data.columns = data.columns.str.strip()

selected_data = data[['country', 'Cases', 'Deaths', 'Recovered']].copy()
selected_data = selected_data.rename(columns={
    "country": "Country",
    "Cases": "Confirmed"
})

selected_data["Active"] = selected_data["Confirmed"] - selected_data["Deaths"] - selected_data["Recovered"]
data = selected_data

if "Date" in data.columns:
    data["Date"] = pd.to_datetime(data["Date"], errors="coerce")

data = data.dropna()
data = data.drop_duplicates()

print("\nDataset Info:")
print(data.info())

print("\nFirst 5 Rows:")
print(data.head())

print("\nStatistical Summary:")
print(data.describe())

total_confirmed = data["Confirmed"].sum()
total_deaths = data["Deaths"].sum()
total_recovered = data["Recovered"].sum()
total_active = data["Active"].sum()

print("\nMissing Values per Column:")
print(data.isnull().sum())

data_cleaned = data.dropna()

print("\nShape of DataFrame after dropping missing values:", data_cleaned.shape)
print("\nMissing Values per Column after dropping NaNs:")
print(data_cleaned.isnull().sum())

total_confirmed_cleaned = data_cleaned["Confirmed"].sum()
total_deaths_cleaned = data_cleaned["Deaths"].sum()
total_recovered_cleaned = data_cleaned["Recovered"].sum()
total_active_cleaned = data_cleaned["Active"].sum()

print(f"\nTotal Confirmed Cases (Cleaned): {total_confirmed_cleaned:,.0f}")
print(f"Total Deaths (Cleaned): {total_deaths_cleaned:,.0f}")
print(f"Total Recovered Cases (Cleaned): {total_recovered_cleaned:,.0f}")
print(f"Total Active Cases (Cleaned): {total_active_cleaned:,.0f}")

data_cleaned = data.dropna()

print("\nShape of DataFrame after dropping missing values:", data_cleaned.shape)
print("\nMissing Values per Column after dropping NaNs:")
print(data_cleaned.isnull().sum())

print("\nTOTAL CONFIRMED:", total_confirmed)
print("TOTAL DEATHS:", total_deaths)
print("TOTAL RECOVERED:", total_recovered)
print("TOTAL ACTIVE:", total_active)

top_countries = data_cleaned.groupby('Country')['Confirmed'].sum().nlargest(10)

plt.figure(figsize=(10,5))
top_countries.plot(kind="bar")
plt.title("Top 10 Affected Countries")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(6,6))
data[["Confirmed","Deaths","Recovered"]].sum().plot(kind="pie", autopct="%1.1f%%")
plt.title("Case Distribution")
plt.ylabel("")
plt.show()

plt.figure(figsize=(7,5))
sns.scatterplot(x="Confirmed", y="Deaths", data=data)
plt.title("Confirmed vs Deaths")
plt.show()

plt.figure(figsize=(7,5))
sns.heatmap(data[["Confirmed","Deaths","Recovered","Active"]].corr(), annot=True, cmap="Blues")
plt.title("Correlation Heatmap")
plt.show()

fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=("Top Countries", "Case Distribution", "Confirmed vs Deaths", "Recovered vs Active"),
    specs=[[{"type":"bar"}, {"type":"pie"}],
           [{"type":"scatter"}, {"type":"scatter"}]]
)

fig.add_trace(
    go.Bar(x=top_countries.index, y=top_countries.values),
    row=1, col=1
)

fig.add_trace(
    go.Pie(labels=["Confirmed","Deaths","Recovered"],
           values=[total_confirmed, total_deaths, total_recovered]),
    row=1, col=2
)

fig.add_trace(
    go.Scatter(x=data["Confirmed"], y=data["Deaths"], mode="markers"),
    row=2, col=1
)

fig.add_trace(
    go.Scatter(x=data["Recovered"], y=data["Active"], mode="markers"),
    row=2, col=2
)

fig.update_layout(
    title="COVID-19 Interactive Dashboard",
    height=800,
    showlegend=False
)

fig.show()

print("\nINSIGHTS:")
print("1. Top affected country:", top_countries.index[0])
print("2. Highest confirmed cases:", data_cleaned["Confirmed"].max())
print("3. Highest deaths:", data_cleaned["Deaths"].max())
print(f"4. Recovery rate approx: {round((total_recovered_cleaned/total_confirmed_cleaned)*100, 2)}%")